Repository PedroChaparro/PI202202-alako-backend, pull requests merged in 2022-10, with the labels that each got.

#17 Pull Request about US06 and US07
  .gitignore
  docker/scala_api/README.md
  docker/scala_api/app/controllers/restApiScala.scala
  docker/scala_api/build.sbt
  docker/scala_api/conf/application.conf
  docker/scala_api/conf/logback.xml
  docker/scala_api/conf/routes
  docker/scala_api/project/build.properties
  docker/scala_api/project/plugins.sbt
  docker/vectorize_api/src/api.py
Labels: S2

#16 Algoritmo de búsqueda coseno de similitud
  docker/.gitignore
  docker/cosine/README.md
  docker/cosine/build.sbt
  docker/cosine/cosine_similarity.scala
  docker/cosine/project/plugins.sbt
  docker/docker-compose.yml
  docker/files/data/data.json
Labels: S2

#35 Limit results number
  docker/cosine/cosine_similarity.scala
Labels: enhancement

#36 Create README.md
  README.md
Labels: documentation

#37 Final Deploy 🏁
  .gitignore
  docker/.gitignore
  docker/README.md
  docker/compose-addfile.yml
  docker/compose-all.yml
  docker/compose-build-cosine.yml
  docker/compose-build-scala-api.yml
  docker/compose-master.yml
  docker/compose-worker.yml
  docker/cosine/README.md
  docker/cosine/build-cosine.sh
  docker/cosine/build.sbt
  docker/cosine/cosine_similarity.scala
  docker/cosine/project/plugins.sbt
  docker/delete-hdfs.sh
  docker/downloadPackages.sh
  docker/files/.bashrc
  docker/files/data/data.json
  docker/files/jar/.gitkeep
  docker/files/jar/cosine-test.sh
  docker/files/pkg/.gitkeep
  docker/hadoop/Dockerfile
  docker/hadoop/add-file.sh
  docker/hadoop/core-site.xml
  docker/hadoop/hdfs-site.xml
  docker/hadoop/init-master.sh
  docker/hadoop/init-worker.sh
  docker/hadoop/start-dfs-datanode.sh
  docker/hadoop/start-dfs-namenode.sh
  docker/hadoop/start-dfs-secondary.sh
  docker/hadoop/start-dfs.sh
  docker/scala_api/Dockerfile
  docker/scala_api/README.md
  docker/scala_api/app/controllers/restApiScala.scala
  docker/scala_api/build-scala-api.sh
  docker/scala_api/build.sbt
  docker/scala_api/conf/application.conf
  docker/scala_api/conf/logback.xml
  docker/scala_api/conf/routes
  docker/scala_api/init.sh
  docker/scala_api/project/build.properties
  docker/scala_api/project/plugins.sbt
  docker/sparkmaster/Dockerfile
  docker/sparkmaster/init.sh
  docker/sparkworker/Dockerfile
  docker/sparkworker/init.sh
  docker/vectorize_api/Dockerfile
  docker/vectorize_api/README.md
  docker/vectorize_api/requirements.txt
  docker/vectorize_api/src/api.py
  docker/vectorize_api/src/model.py
Labels: S2, S3

#34 Clear results from map
  docker/scala_api/app/controllers/restApiScala.scala
Labels: enhancement
